### PR TITLE
Allow for upload/download from/to memory

### PR DESCRIPTION
**Pull request by AndreyNazarchuk**
Useful if files are accessed rarely and should not be saved to avoid I/O bottleneck

### CODE REVIEW

**Comment by SociallyDev** [comment]
Thank you! I've committed the changes.

**Comment by AndreyNazarchuk** [comment]
Awesome!
I saw you're talking about a rewrite...can you make sure this option is available in the new version?
Or maybe I could help you with it!

BTW I don't know how Composer works so when do you think the updates will be available there?

**Comment by SociallyDev** [comment]
Sure! This'll definitely be in there.
I'd love to have your help. Just add me on any social you're on; I'm @SociallyDev everywhere.
Composer should have the latest version by now.

**Comment by AndreyNazarchuk** [comment]
Cool. Composer is automatic?

**Comment by SociallyDev** [comment]
Composer downloads (typically the latest version of) projects from an NPM like package registry called Packagist. Packages can either be manually saved or synced with GitHub. Spaces-API's Packagist project is automatically synced with its GitHub counterpart.

**Pull request merged**
